### ISSUE TITLE
Get email from ORCID member API

### ISSUE THREAD

**Issue by laurenwalker** [DataONEorg/d1_portal_servlet#3] opened 2022-05-31 17:59 UTC
When we get the first and last name of the person from the ORCID API, we should also attempt to get the email address and save it to the DataONE account.

**Comment by mbjones** [comment] 2023-12-19 22:01
Duplicate of ticket https://github.com/DataONEorg/d1_portal/issues/3

**Closed as completed by mbjones** 2023-12-19 22:01 UTC
Labels: enhancement

**Comment by mbjones** [comment] 2025-09-30 00:12
Closed as duplicate, kept other ticket as it has more detail.
